'use client';
import './discovery.css';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import Nav from '@/components/Nav';

const moods = ['Focused', 'Warm', 'Restless', 'Weightless'];
export default function Discover() {
  const [query, setQuery] = useState(''); const [seed, setSeed] = useState(null); const [filters, setFilters] = useState({ mood: '', energy: '', tempo: '', vocals: '', genre: '' });
  const [results, setResults] = useState([]); const [mode, setMode] = useState(null); const [queryId, setQueryId] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [user, setUser] = useState(null); const [playlists, setPlaylists] = useState([]); const [notice, setNotice] = useState('');
  useEffect(() => { fetch('/api/auth/session').then((r) => r.json()).then(({ user }) => { setUser(user); if (user) fetch('/api/playlists').then((r) => r.json()).then((d) => setPlaylists(d.playlists || [])); }); }, []);
  async function search(e) { e.preventDefault(); setError(''); setNotice(''); setLoading(true); const r = await fetch('/api/recommendations', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ query, seed, filters }) }); const data = await r.json(); setLoading(false); if (!r.ok) return setError(data.error); setResults(data.results); setMode(data.mode); setQueryId(data.queryId); }
  async function feedback(track, action) { if (!user) { window.location.href = '/login'; return; } const r = await fetch('/api/feedback', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ track, action, queryId }) }); const data = await r.json(); if (!r.ok) return setNotice(data.error); setNotice(action === 'REJECT' ? 'Marked as not for you.' : 'Saved to your listening feedback.'); if (action === 'REJECT') setResults((items) => items.filter((item) => item.providerId !== track.providerId)); }
  async function addToPlaylist(track, playlistId) { if (!playlistId) return; if (!user) { window.location.href = '/login'; return; } const r = await fetch(`/api/playlists/${playlistId}/tracks`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ track }) }); const data = await r.json(); setNotice(r.ok ? 'Added to playlist.' : data.error); }
  return <main><Nav /><section className="discover-header"><p className="eyebrow">DISCOVERY STATION</p><h1>What do you want to hear?</h1><p>Start with a feeling—or a song already in your head.</p></section><section className="discovery-shell"><form className="search-panel" onSubmit={search}><div className="search-line"><span aria-hidden="true">⌕</span><input aria-label="Describe music you want to hear" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="upbeat study music without heavy vocals" /><button className="button" disabled={loading}>{loading ? 'Finding…' : 'Discover'}</button></div><div className="seed-row"><label>Seed song<input value={seed?.title || ''} onChange={(e) => setSeed(e.target.value ? { title: e.target.value, artist: 'Selected seed' } : null)} placeholder="Search for a song to begin with" /></label>{seed && <button type="button" className="seed-chip" onClick={() => setSeed(null)}>Starting from: {seed.title} <span aria-label="Remove seed">×</span></button>}</div><div className="filter-row"><select aria-label="Mood" value={filters.mood} onChange={(e) => setFilters({ ...filters, mood: e.target.value })}><option value="">Mood</option>{moods.map((m) => <option key={m}>{m}</option>)}</select>{[['energy', 'Energy'], ['tempo', 'Tempo'], ['vocals', 'Vocals'], ['genre', 'Genre']].map(([key, label]) => <input key={key} aria-label={label} value={filters[key]} onChange={(e) => setFilters({ ...filters, [key]: e.target.value })} placeholder={label} />)}</div></form>{error && <p className="form-error" role="alert">{error}</p>}{notice && <p className="notice" role="status">{notice}</p>}<section className="results-area" aria-live="polite">{!loading && !results.length && <div className="empty-state"><span>♫</span><h2>Your next turn starts here.</h2><p>Give us a mood, a moment, or a seed song. Results will show what the recommendation service returns.</p></div>}{mode === 'mock' && <p className="mock-note">Development mock results — connect the recommendation service to receive live matches.</p>}{loading && <div className="empty-state"><span className="pulse">◌</span><h2>Listening for a direction…</h2></div>}{results.map((track, index) => <TrackResult key={track.providerId || index} track={track} playlists={playlists} onFeedback={feedback} onAdd={addToPlaylist} />)}</section></section></main>;
}

function TrackResult({ track, playlists, onFeedback, onAdd }) { const [playing, setPlaying] = useState(false); return <article className="track-row"><div className="cover">{track.coverArtUrl ? <img src={track.coverArtUrl} alt={`Cover art for ${track.title}`} /> : <span aria-hidden="true">{track.title.slice(0, 1)}</span>}</div><div className="track-main"><p className="track-title">{track.title}</p><p>{track.artist}{track.album ? ` · ${track.album}` : ''}</p><p className="match-reason">{track.why}</p></div><div className="track-actions">{track.previewUrl && <button className="icon-button" aria-label={`${playing ? 'Pause' : 'Play'} preview of ${track.title}`} onClick={() => setPlaying(!playing)}>{playing ? 'Ⅱ' : '▶'}{playing && <audio autoPlay src={track.previewUrl} onEnded={() => setPlaying(false)} />}</button>} {track.providerUrl && <a className="icon-button" href={track.providerUrl} target="_blank" rel="noreferrer" aria-label={`Open ${track.title} on its music provider`} onClick={() => onFeedback(track, 'OPEN')}>↗</a>}<button className="save-button" onClick={() => onFeedback(track, 'SAVE')}>Save</button><button className="reject-button" onClick={() => onFeedback(track, 'REJECT')} aria-label={`Reject ${track.title}`}>×</button>{playlists.length > 0 ? <select aria-label={`Add ${track.title} to playlist`} defaultValue="" onChange={(e) => { onAdd(track, e.target.value); e.target.value = ''; }}><option value="">Add to playlist</option>{playlists.map((p) => <option key={p.id} value={p.id}>{p.title}</option>)}</select> : <Link className="playlist-link" href="/playlists">+ playlist</Link>}</div></article>; }
